version: 1.0.0

services:
  website:
    container_name: website
    build:
      context: ../website
      dockerfile: ../docker/Dockerfile.${MODE:-dev}
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_KEY=${VITE_API_KEY}
    ports:
      - 4173:4173
    volumes:
      - ../website:/app
      - /app/node_modules
